### PR TITLE
add pmtiles support

### PR DESCRIPTION
**Pull request by greensopinion**

### CODE REVIEW

**Comment by josxha** [comment]
Hi @greensopinion! It's nice to see that you want to add native support for PMTiles to your vector_map_tiles package!
I'm the author of the [vector_map_tiles_pmtiles](https://pub.dev/packages/vector_map_tiles_pmtiles) package. If I knew that you have concidered to add support yourself wouldn't have created the package. 😅 

I wanted to share some experience with pmtiles. 
- The max and min zoom are both required for pmtiles, so you could use the values from the header directly.
- Protomap is sadly not compatible with openmaptiles styles. Have you planned to add a protomaps theme as `ProvidedTheme`?

**Comment by greensopinion** [comment]
@josxha very cool, I wasn't aware of your support for pmtiles! Thanks for pointing that out. I won't merge this change, since you've already got it covered. Feel free to issue a pull request on the README of this package - it would be good to make your plugin more discoverable.

> The max and min zoom are both required for pmtiles, so you could use the values from the header directly.

I'm not sure what you mean!

> Protomap is sadly not compatible with openmaptiles styles. Have you planned to add a protomaps theme as ProvidedTheme?

What aspect is not compatible? Can you elaborate?

**Comment by greensopinion** [comment]
suggested changes: https://github.com/josxha/flutter_map_plugins/pull/34

**Comment by josxha** [comment]
> I won't merge this change, since you've already got it covered. Feel free to issue a pull request on the README of this package - it would be good to make your plugin more discoverable.

Alright, if you change your mind and want to have build-in pmtiles support in the future I'm completely fine with it. Until then I keep maintaining the tile provider package. 👍I'll do a pull request with the documentation tomorrow.

 > I'm not sure what you mean

I was looking though your implementation and saw that you let the user provide the min and max zoom for the PmTilesVectorTileProvider
```dart
PmTilesVectorTileProvider(
      {required this.archive,
      required this.type,
      required this.minimumZoom,
      required this.maximumZoom});
```

and since both parameters are required fields in the PMTiles header, those values can be used directly from the archive:
```dart
  @override
  int get maximumZoom => archive.maxZoom;

  @override
  int get minimumZoom => archive.minZoom;
```

...but this information doesn't readdy matter now any more i guess.

> What aspect is not compatible? Can you elaborate?

I haven't compared Protomaps and openmaptiles styles in detail yet but if you try to use Protomaps tile data with the included osm libery light theme only some layers get drawn. The result looks something like this:

image

By using one of the default protomaps themes (e.g. from the [node package](https://unpkg.com/browse/protomaps-themes-base@2.0.0-alpha.5/dist/layers/)) all details show up fine. For more information see https://github.com/josxha/flutter_map_plugins/issues/17. 
I think same incompatibility is with openmaptiles and mapbox themes if I'm not wrong?

**Comment by greensopinion** [comment]
thanks @josxha !

>  if you try to use Protomaps tile data with the included osm libery light theme only some layers get drawn

Generally the theme has to match the tile data format. From what you've observed, Protomaps vector tiles provide tile data with the same protobuf schema but different conventions, so [osm](https://osmfoundation.org/) styles don't work with Protomaps.

> I think same incompatibility is with openmaptiles and mapbox themes if I'm not wrong?

Mapbox themes work great with open map tiles. You can try it out from the [examples project](https://github.com/greensopinion/flutter-vector-map-tiles-examples).

I'm going to close this PR off, since there's nothing left to do here.

**Comment by josxha** [comment]
> Mapbox themes work great with open map tiles. You can try it out from the [examples project](https://github.com/greensopinion/flutter-vector-map-tiles-examples).

Oh, that's nice. Good to know!

> Feel free to issue a pull request on the README of this package - it would be good to make your plugin more discoverable.

I opened https://github.com/greensopinion/flutter-vector-map-tiles/pull/200 for it. 👍

**Pull request closed without merging**
