### PR TITLE
Upgrade flutter map dependency

### PR DESCRIPTION
**Pull request by Wackymax**

### CODE REVIEW

**Comment by Koboo** [comment]
Hey @Wackymax 
Could you update the PR to directly update `flutter_map` to `^7.0.2` and `latlong2` to version `0.9.1`. Both are the newest versions.

**Comment by Wackymax** [comment]
I didn't want to do that because it would force everyone using this lib to update to that version. The ^ will automatically let flutter pub use the latest version if it can.On 29 Jul 2024, at 10:55, Koboo ***@***.***> wrote:﻿
Hey @Wackymax
Could you update the PR to directly update flutter_map to ^7.0.2 and latlong2 to version 0.9.1. Both are the newest versions.

**Comment by greensopinion** [comment]
I've tried this PR with the example and the map comes up blank. It's working fine with the `main` branch. Anyone had success with the example app?

**Comment by greensopinion** [comment]
merged #206, thanks for the contribution

**Pull request closed without merging**
