### PR TITLE
Feature/web support

### PR DESCRIPTION
**Pull request by Nacho-Larreta**
Added the necessary code to support web

### CODE REVIEW

**Comment by greensopinion** [comment]
Thanks for the contribution!

We've looked into web support before, but decided not to take it on because of poor performance. https://github.com/greensopinion/flutter-vector-map-tiles/issues/64#issuecomment-1846343890

Is web performance good enough to make this effort worthwhile?

**Comment by Nacho-Larreta** [comment]
I taken the time to make it work because I need it on a project that I'm working, I'm testing it using an open map tile server running locally with vectors (pbf) and as far as I tested it it's working fine for me. 
It could be perform better I suppose, but as an MMF it's awesome to have it. 
I'm working on the map implementation right now on my web and mobile app, if I see that the performance is not good enough I'm going to review it more in deep to make it better.

**Comment by Nacho-Larreta** [comment]
Screenshot 2024-10-20 at 12 14 20 AM

I'm on the phase to create my re usable component, it's not really fancy the page. But I wanted to show you as screenshot that it's working.

**Comment by greensopinion** [comment]
This is really good. On my mac with the example app I'm getting about the same responsiveness with web as with a mac-native.

I've added an alternative implementation as pull #216. There are a few minor differences with code structure and naming, also managing the lifecycle of the IndexedDB database. 

I'm not sure how web support will be shown given the  `dart:io` imports and `path_provider` dependency. Any ideas are welcome: https://pub.dev/packages/vector_map_tiles/score

**Comment by Nacho-Larreta** [comment]
Looks like awesome, much cleaner than my code, I'm going to close this PR to continue from your latest code!

**Pull request closed without merging**
